**1.Pandas**

In [1]:
import pandas as pd
data = pd.read_csv('ipf_lifts.csv', sep=',')

In [4]:
data.head()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205.0,140.0,225.0,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24.0,24-34,NaN,67.5,67.5,225.0,132.5,235.0,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245.0,157.5,270.0,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195.0,110.0,240.0,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240.0,140.0,215.0,5,1985-08-03,IPF,World Games

1. Знайдіть рекорди для кожної статі та кожного підрозділу в кожному з 3-х -
жим лежачи(best3bench_kg), присідання(best3squat_kg) та станова
тяга(best3deadlift_kg)).

In [18]:
best_bench_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3bench_kg']
best_bench_sex

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\995558809.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_bench_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3bench_kg']

sex  equipment   event
F    Raw         B        147.5
                 SBD      151.5
     Single-ply  B        235.0
                 SBD      230.0
M    Raw         B        320.0
                 SBD      290.0
     Single-ply  B        401.0
                 SB       162.5
                 SBD      415.0
     Wraps       SBD      260.0
Name: best3bench_kg, dtype: float64

In [19]:
best_bench_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3bench_kg']
best_bench_division

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\2255053799.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_bench_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3bench_kg']

division    weight_class_kg  sex
Heavy       100              M      280.0
            105              M      322.5
            67.5+            F      192.5
            72               F      175.0
            75               F      152.5
                                    ...
Super       75+              F      180.0
SuperHeavy  120              M      290.0
            120+             M      405.0
            84               F      182.5
            84+              F      205.0
Name: best3bench_kg, Length: 268, dtype: float64

In [21]:
best_squat_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3squat_kg']
best_squat_sex

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\3526290300.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_squat_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3squat_kg']

sex  equipment   event
F    Raw         B          NaN
                 SBD      273.0
     Single-ply  B          NaN
                 SBD      322.5
M    Raw         B          NaN
                 SBD      470.0
     Single-ply  B          NaN
                 SB       290.0
                 SBD      490.0
     Wraps       SBD      400.0
Name: best3squat_kg, dtype: float64

In [24]:
best_squat_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3squat_kg']
best_squat_division

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\4041733120.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_squat_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3squat_kg']

division    weight_class_kg  sex
Heavy       100              M      385.0
            105              M      432.0
            67.5+            F      305.0
            72               F      248.5
            75               F      220.0
                                    ...
Super       75+              F      267.5
SuperHeavy  120              M      390.0
            120+             M      475.0
            84               F      260.0
            84+              F      310.5
Name: best3squat_kg, Length: 268, dtype: float64

In [23]:
best_deadlift_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3deadlift_kg']
best_deadlift_sex

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\3153266620.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_deadlift_sex = data.groupby(['sex', 'equipment', 'event']).max()['best3deadlift_kg']

sex  equipment   event
F    Raw         B          NaN
                 SBD      252.5
     Single-ply  B          NaN
                 SBD      270.5
M    Raw         B          NaN
                 SBD      398.5
     Single-ply  B          NaN
                 SB         NaN
                 SBD      420.0
     Wraps       SBD      385.0
Name: best3deadlift_kg, dtype: float64

In [25]:
best_deadlift_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3deadlift_kg']
best_deadlift_division

C:\Users\Академия 33\AppData\Local\Temp\ipykernel_13900\689592385.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  best_deadlift_division = data.groupby(['division', 'weight_class_kg', 'sex']).max()['best3deadlift_kg']

division    weight_class_kg  sex
Heavy       100              M      345.0
            105              M      375.0
            67.5+            F      245.0
            72               F      248.5
            75               F      225.0
                                    ...
Super       75+              F      242.5
SuperHeavy  120              M      420.0
            120+             M      355.0
            84               F      220.0
            84+              F      247.5
Name: best3deadlift_kg, Length: 268, dtype: float64

2. Загальна кількість перемог кожного, приймаючи за перемогу 1-е місце. Збережіть результати у вторинному DataFrame.

In [27]:
winners = data[data['place'] == '1'].groupby('name').agg(winners_number=('place', 'count'))
winners

                           winners_number
name
A Ernandos-Ortega                       1
A. Raface                               1
Aarre Käpylä                            2
Ab Wolders                              3
Abdulkarim Karaman                      4
...                                   ...
Éva Makrai                              2
Øyvind Bjørnsen                         1
Þórunn Brynja Jónasdóttir               1
Štefan Koľšovský                        7
Štěpánka Židová                         1

[3328 rows x 1 columns]

In [35]:
winners.to_csv('all_winners.csv')

3. Використовуйте DataFrame з вправи 2, щоб показати для кожного наявність підрозділу та статті, наявного з серед учасників, які будь-коли брали участь у цьому дивізіоні.

In [40]:
data = data.merge(winners, how='left', on='name') #До data доєднуємо датафрейм winners і заповнюємо по кожному його загальну кількість перемог
data

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name,winners_number_x,winners_number_y,winners_number
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205.0,140.0,225.0,1,1985-08-03,IPF,World Games,21.0,21.0,21.0
1,David Mannering,M,SBD,Single-ply,24.0,24-34,NaN,67.5,67.5,225.0,132.5,235.0,2,1985-08-03,IPF,World Games,NaN,NaN,NaN
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245.0,157.5,270.0,3,1985-08-03,IPF,World Games,4.0,4.0,4.0
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195.0,110.0,240.0,4,1985-08-03,IPF,World Games,4.0,4.0,4.0
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240.0,140.0,215.0,5,1985-08-03,IPF,World Games,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41147,Chien-Hsiung Chao,M,B,Single-ply,NaN,NaN,Open,126.5,125+,NaN,202.5,NaN,12,1995-06-25,IPF,World Bench Press Championships,NaN,NaN,NaN
41148,Oleg Gordynetz,M,B,Single-ply,NaN,NaN,Open,137.5,125+,NaN,202.5,NaN,13,1995-06-25,IPF,World Bench Press Championships,NaN,NaN,NaN
41149,Clive Lambert,M,B,Single-ply,31.5,24-34,Open,142.2,125+,NaN,202.5,NaN,14,1995-06-25,IPF,World Bench Press Championships,NaN,NaN,NaN
41150,Peter Brath,M,B,Single-ply,21.5,20-23,Open,125.5,125+,NaN,180.0,NaN,15,1995-06-25,IPF,World Bench Press Championships,NaN,NaN,NaN
41151,Valery Sidorenko,M,B,Single-ply,38.5,35-39,Open,142.0,125+,NaN,NaN,NaN,DQ,1995-06-25,IPF,World Bench Press Championships,NaN,NaN,NaN

In [41]:
division_best = data.groupby(['division', 'weight_class_kg', 'sex']).winners_number.max()
print(division_best)

division    weight_class_kg  sex
Heavy       100              M       9.0
            105              M      11.0
            67.5+            F      22.0
            72               F      17.0
            75               F      17.0
                                    ...
Super       75+              F      22.0
SuperHeavy  120              M       6.0
            120+             M       8.0
            84               F       4.0
            84+              F      22.0
Name: winners_number, Length: 268, dtype: float64

**2. SQL**